/*
 * ember_rl_inference.cpp  —  M2: On-Board RL Inference
 *
 * Implements the 16-feature normalisation and DQN forward pass that mirrors
 * the Python predict.py used by the web server (src/predict.py).
 *
 * Network: 16 → 64 (ReLU) → 64 (ReLU) → 2 (linear)
 * Weights loaded from ember_rl_policy.h (auto-generated by export_policy.py).
 */

#include "ember_rl_inference.h"
#include "ember_rl_policy.h"
#include <cmath>
#include <cstdio>

/* ── Alarm state (persists across calls) ───────────────────────────────────── */
static int prev_alarm = 0;

/* ============================================================================
 * Normalisation constants  (must match src/data_loader.py NORM dict)
 * ========================================================================== */
#define NORM_PM1_MAX        500.0f
#define NORM_PM25_MAX       500.0f
#define NORM_PM10_MAX       600.0f
#define NORM_TVOC_MAX     10000.0f
#define NORM_ECO2_MIN       400.0f
#define NORM_ECO2_RANGE    9600.0f   /* 10000 - 400 */
#define NORM_TEMP_MIN       -40.0f
#define NORM_TEMP_RANGE     165.0f   /* 125 - (-40) */
#define NORM_HUM_MAX        100.0f
#define NORM_PRES_MIN       300.0f
#define NORM_PRES_RANGE     800.0f
#define NORM_GAS_LOG_MAX      7.301f /* log10(20 000 000) */
#define NORM_AQI_MAX        500.0f

/* ============================================================================
 * AQI helpers  (mirrors src/aqi_engine.py — used to compute obs[14])
 * ========================================================================== */

static float _aqi_interp(float v,
    const float* c_lo, const float* c_hi,
    const float* i_lo, const float* i_hi, int n)
{
    for (int k = 0; k < n; k++) {
        if (v >= c_lo[k] && v <= c_hi[k])
            return i_lo[k] + (v - c_lo[k]) * (i_hi[k] - i_lo[k]) / (c_hi[k] - c_lo[k]);
    }
    return (v > c_hi[n-1]) ? i_hi[n-1] : 0.0f;
}

static float pm25_to_aqi(float pm) {
    static const float cl[] = {0.0f, 12.1f, 35.5f,  55.5f, 150.5f, 250.5f};
    static const float ch[] = {12.0f, 35.4f, 55.4f, 150.4f, 250.4f, 500.4f};
    static const float il[] = {0,  51, 101, 151, 201, 301};
    static const float ih[] = {50, 100, 150, 200, 300, 500};
    return _aqi_interp(pm, cl, ch, il, ih, 6);
}

static float pm10_to_aqi(float pm) {
    static const float cl[] = {0,  55,  155, 255, 355, 425};
    static const float ch[] = {54, 154, 254, 354, 424, 604};
    static const float il[] = {0,  51, 101, 151, 201, 301};
    static const float ih[] = {50, 100, 150, 200, 300, 500};
    return _aqi_interp(pm, cl, ch, il, ih, 6);
}

static float mq_to_aqi(float mq_v) {
    if (mq_v < 0.3f)  return   0.0f;
    if (mq_v < 0.6f)  return  50.0f;
    if (mq_v < 1.0f)  return 100.0f;
    if (mq_v < 1.5f)  return 150.0f;
    if (mq_v < 2.0f)  return 200.0f;
    if (mq_v < 2.5f)  return 300.0f;
    return 500.0f;
}

static float tvoc_to_aqi(float tvoc) {
    if (tvoc <= 0.0f) return 0.0f;
    static const float cl[] = {0,   65,  220,  660, 2200, 5500};
    static const float ch[] = {65, 220,  660, 2200, 5500, 10000};
    static const float il[] = {0,  51,  101,  151,  201,  301};
    static const float ih[] = {50, 100, 150,  200,  300,  500};
    return _aqi_interp(tvoc, cl, ch, il, ih, 6);
}

static float eco2_to_aqi(float eco2) {
    if (eco2 <= 400.0f) return 0.0f;
    static const float cl[] = {400,  600, 1000, 1500, 2500, 5000};
    static const float ch[] = {600, 1000, 1500, 2500, 5000, 10000};
    static const float il[] = {0,   51,  101,  151,  201,  301};
    static const float ih[] = {50, 100,  150,  200,  300,  500};
    return _aqi_interp(eco2, cl, ch, il, ih, 6);
}

static float composite_aqi(float pm25, float pm10,
                            float mq_v, float tvoc, float eco2)
{
    float s[5] = {
        pm25_to_aqi(pm25),
        pm10_to_aqi(pm10),
        mq_to_aqi(mq_v),
        tvoc_to_aqi(tvoc),
        eco2_to_aqi(eco2)
    };
    float best = 0.0f;
    int   above = 0;
    for (int i = 0; i < 5; i++) {
        if (s[i] > best) best = s[i];
        if (s[i] > 100.0f) above++;
    }
    if (above >= 2) best *= 1.20f;
    return (best > 500.0f) ? 500.0f : best;
}

/* ============================================================================
 * Feature normalisation  (mirrors src/data_loader.py normalize_obs())
 * ========================================================================== */

static void build_obs(
    uint16_t pm1_0, uint16_t pm2_5, uint16_t pm10,
    float temperature, float humidity, float pressure, float gas_res,
    float mq_analog, int mq_digital,
    uint16_t tvoc, uint16_t eco2,
    float aqi,
    float* obs)   /* obs[16] output */
{
    obs[0]  = (float)pm1_0 / NORM_PM1_MAX;
    obs[1]  = (float)pm2_5 / NORM_PM25_MAX;
    obs[2]  = (float)pm10  / NORM_PM10_MAX;
    obs[3]  = (float)tvoc  / NORM_TVOC_MAX;

    float eco2_shifted = (float)eco2 - NORM_ECO2_MIN;
    obs[4]  = (eco2_shifted > 0.0f) ? (eco2_shifted / NORM_ECO2_RANGE) : 0.0f;

    obs[5]  = (temperature - NORM_TEMP_MIN)  / NORM_TEMP_RANGE;
    obs[6]  = humidity  / NORM_HUM_MAX;
    obs[7]  = (pressure - NORM_PRES_MIN)     / NORM_PRES_RANGE;

    float gas_clamped = (gas_res < 10000.0f) ? 10000.0f : gas_res;
    obs[8]  = log10f(gas_clamped) / NORM_GAS_LOG_MAX;

    obs[9]  = mq_analog;               /* already 0–1 (ADC ratio, 3.3V ref) */
    obs[10] = (float)mq_digital;

    obs[11] = 1.0f;   /* pms_valid        — PMS5003 assumed online */
    obs[12] = 0.0f;   /* ens160_available — ENS160 disconnected    */
    obs[13] = 1.0f;   /* bme680_available — BME680 assumed online  */

    obs[14] = aqi / NORM_AQI_MAX;
    obs[15] = (float)prev_alarm;

    /* Clip to [0, 1] */
    for (int i = 0; i < 16; i++) {
        if (obs[i] < 0.0f) obs[i] = 0.0f;
        if (obs[i] > 1.0f) obs[i] = 1.0f;
    }
}

/* ============================================================================
 * NN forward pass  —  16 → 64 (ReLU) → 64 (ReLU) → 2 (linear)
 * ========================================================================== */

static void forward(const float* obs, float* q_out)
{
    float h1[64], h2[64];

    /* Layer 1: 16 → 64, ReLU */
    for (int i = 0; i < 64; i++) {
        float sum = EMBER_B1[i];
        for (int j = 0; j < 16; j++) sum += EMBER_W1[i][j] * obs[j];
        h1[i] = (sum > 0.0f) ? sum : 0.0f;
    }

    /* Layer 2: 64 → 64, ReLU */
    for (int i = 0; i < 64; i++) {
        float sum = EMBER_B2[i];
        for (int j = 0; j < 64; j++) sum += EMBER_W2[i][j] * h1[j];
        h2[i] = (sum > 0.0f) ? sum : 0.0f;
    }

    /* Output: 64 → 2, linear */
    for (int i = 0; i < 2; i++) {
        float sum = EMBER_B3[i];
        for (int j = 0; j < 64; j++) sum += EMBER_W3[i][j] * h2[j];
        q_out[i] = sum;
    }
}

/* ============================================================================
 * Public API
 * ========================================================================== */

void ember_inference_reset(void)
{
    prev_alarm = 0;
}

EmberInferenceResult_t ember_inference_run(
    uint16_t pm1_0,  uint16_t pm2_5, uint16_t pm10,
    float    temperature, float humidity, float pressure, float gas_res,
    float    mq_analog,   int   mq_digital,
    uint16_t tvoc,   uint16_t eco2)
{
    /* 1. Compute composite AQI (for obs[14]) */
    float mq_v = mq_analog * 3.3f;
    float aqi  = composite_aqi((float)pm2_5, (float)pm10,
                               mq_v, (float)tvoc, (float)eco2);

    /* 2. Build normalised observation vector */
    float obs[16];
    build_obs(pm1_0, pm2_5, pm10,
              temperature, humidity, pressure, gas_res,
              mq_analog, mq_digital,
              tvoc, eco2,
              aqi,
              obs);

    /* 3. Run NN forward pass → Q-values */
    float q[2];
    forward(obs, q);

    /* 4. Pick action with higher Q-value */
    int action = (q[1] > q[0]) ? 1 : 0;
    prev_alarm = action;

    EmberInferenceResult_t result;
    result.alarm_on = action;
    result.q_off    = q[0];
    result.q_on     = q[1];
    result.aqi      = aqi;
    return result;
}
