"""
M2 — Export Policy Weights
Extracts the trained DQN neural network weights from best_model.zip
and writes them as C float arrays into ember_rl_policy.h.

Run this ONCE on your laptop before flashing M2 to the K64F:
    python m2/export_policy.py

Output: m2/ember_rl_policy.h  (then copy to Mbed project)

Network architecture: 16 → 64 (ReLU) → 64 (ReLU) → 2 (linear)
"""

import os
import sys
import numpy as np

ROOT       = os.path.join(os.path.dirname(__file__), '..')
MODEL_PATH = os.path.join(ROOT, 'models', 'best_model.zip')
OUT_PATH   = os.path.join(os.path.dirname(__file__), 'ember_rl_policy.h')

sys.path.insert(0, os.path.join(ROOT, 'src'))

# ── Load the trained DQN model ────────────────────────────────────────────────
try:
    from stable_baselines3 import DQN
except ImportError:
    print("[ERROR] stable_baselines3 not installed.")
    print("        Run: pip install stable-baselines3")
    sys.exit(1)

if not os.path.exists(MODEL_PATH):
    print(f"[ERROR] Model not found: {MODEL_PATH}")
    print("        Run src/train.py first.")
    sys.exit(1)

print(f"[Export] Loading model from {MODEL_PATH} ...")
model = DQN.load(MODEL_PATH)

# ── Extract Q-network layers ──────────────────────────────────────────────────
# SB3 DQN with net_arch=[64,64]:
#   q_net[0] = Linear(16, 64)  ← layer 1
#   q_net[1] = ReLU
#   q_net[2] = Linear(64, 64)  ← layer 2
#   q_net[3] = ReLU
#   q_net[4] = Linear(64,  2)  ← output layer
q_net = model.policy.q_net.q_net

w1 = q_net[0].weight.data.cpu().numpy()   # shape (64, 16)
b1 = q_net[0].bias.data.cpu().numpy()     # shape (64,)
w2 = q_net[2].weight.data.cpu().numpy()   # shape (64, 64)
b2 = q_net[2].bias.data.cpu().numpy()     # shape (64,)
w3 = q_net[4].weight.data.cpu().numpy()   # shape (2, 64)
b3 = q_net[4].bias.data.cpu().numpy()     # shape (2,)

print(f"[Export] Layer 1: {w1.shape}  bias {b1.shape}")
print(f"[Export] Layer 2: {w2.shape}  bias {b2.shape}")
print(f"[Export] Output : {w3.shape}  bias {b3.shape}")


# ── Helper: write a 2D float array as a C array literal ──────────────────────
def fmt_array_2d(name, arr, rows, cols):
    lines = [f"static const float {name}[{rows}][{cols}] = {{"]
    for i in range(rows):
        row_vals = ", ".join(f"{arr[i, j]:.8f}f" for j in range(cols))
        comma = "," if i < rows - 1 else ""
        lines.append(f"    {{ {row_vals} }}{comma}")
    lines.append("};")
    return "\n".join(lines)


def fmt_array_1d(name, arr, n):
    vals = ", ".join(f"{arr[i]:.8f}f" for i in range(n))
    return f"static const float {name}[{n}] = {{ {vals} }};"


# ── Write header file ─────────────────────────────────────────────────────────
with open(OUT_PATH, "w", encoding="utf-8") as f:
    f.write("""\
/*
 * ember_rl_policy.h  —  AUTO-GENERATED by m2/export_policy.py
 * DO NOT EDIT BY HAND.
 *
 * DQN policy network weights for on-board RL inference.
 * Network: 16 → 64 (ReLU) → 64 (ReLU) → 2 (linear)
 *
 * Action 0 = ALARM_OFF
 * Action 1 = ALARM_ON
 */
#ifndef EMBER_RL_POLICY_H
#define EMBER_RL_POLICY_H

/* ── Layer 1: Linear(16 → 64) ── */
""")
    f.write(fmt_array_2d("EMBER_W1", w1, 64, 16) + "\n\n")
    f.write(fmt_array_1d("EMBER_B1", b1, 64) + "\n\n")

    f.write("/* ── Layer 2: Linear(64 → 64) ── */\n")
    f.write(fmt_array_2d("EMBER_W2", w2, 64, 64) + "\n\n")
    f.write(fmt_array_1d("EMBER_B2", b2, 64) + "\n\n")

    f.write("/* ── Output layer: Linear(64 → 2) ── */\n")
    f.write(fmt_array_2d("EMBER_W3", w3, 2, 64) + "\n\n")
    f.write(fmt_array_1d("EMBER_B3", b3, 2) + "\n\n")

    f.write("#endif /* EMBER_RL_POLICY_H */\n")

print(f"[Export] Done! Written to: {OUT_PATH}")
print(f"[Export] Copy ember_rl_policy.h into your Mbed project.")
