"""
Data loader and preprocessor.

Handles three data sources:
  1. Synthetic CSV  — generated by data_generator.py
  2. Ember hardware CSV — from /sd/data/YYYY-MM-DD.csv on the SD card
  3. Beijing Multi-Site Air Quality dataset (Kaggle) — adapted to our format

All sources are normalised to the same 16-feature observation vector
used by the RL environment (see SYSTEM_DOCUMENTATION.md Section 7.1).
"""

import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

import numpy as np
import pandas as pd
from pathlib import Path
from aqi_engine import compute_composite_aqi, is_dangerous

# ---------------------------------------------------------------------------
# Normalisation constants — maps raw sensor values to [0, 1]
# ---------------------------------------------------------------------------
NORM = {
    'PM1.0':       (0.0, 500.0),
    'PM2.5':       (0.0, 500.0),
    'PM10':        (0.0, 600.0),
    'TVOC':        (0.0, 10000.0),
    'eCO2_min':    400.0,
    'eCO2_range':  9600.0,          # 10000 - 400
    'temperature': (-40.0, 125.0),  # range = 165
    'humidity':    (0.0, 100.0),
    'pressure':    (300.0, 800.0),  # range from 300 base
    'gas_log_max': 7.301,           # log10(20_000_000)
    'MQ_voltage':  (0.0, 3.3),
    'aqi':         (0.0, 500.0),
}

# Column names expected in every loaded CSV (raw format)
REQUIRED_COLS = [
    'PM1.0', 'PM2.5', 'PM10', 'TVOC', 'eCO2',
    'temperature', 'humidity', 'pressure', 'gas',
    'MQ_analog', 'MQ_digital'
]


# ---------------------------------------------------------------------------
# Main loader
# ---------------------------------------------------------------------------

class DataLoader:
    """
    Loads, cleans, engineers features, and normalises air quality CSV data
    into episodes ready for the RL environment.
    """

    def __init__(self, episode_length: int = 60, stride: int = 30):
        """
        Args:
            episode_length: Number of timesteps per episode (60 ≈ 2.5 min).
            stride:         Step between episode start points (for overlap).
        """
        self.episode_length = episode_length
        self.stride = stride

    # -----------------------------------------------------------------------
    # Public loaders
    # -----------------------------------------------------------------------

    def load_synthetic(self, csv_path: str) -> list:
        """Load synthetic CSV produced by data_generator.py."""
        df = pd.read_csv(csv_path, parse_dates=['timestamp'])
        df = self._clean(df)
        df = self._engineer_features(df)
        return self._split_episodes(df)

    def load_hardware(self, csv_path: str) -> list:
        """
        Load a real hardware CSV from the Ember SD card.
        Format: timestamp,PM1.0,PM2.5,PM10,TVOC,eCO2,temperature,humidity,
                pressure,gas,MQ_analog,MQ_digital
        """
        df = pd.read_csv(csv_path, parse_dates=['timestamp'])
        df = self._clean(df)
        # If no aqi_score column, compute it
        if 'aqi_score' not in df.columns:
            df = self._label(df)
        df = self._engineer_features(df)
        return self._split_episodes(df)

    def load_beijing(self, csv_path: str) -> list:
        """
        Adapt the Kaggle Beijing Multi-Site Air Quality dataset.
        File: PRSA_Data_<Station>_20130301-20170228.csv
        Columns used: PM2.5, PM10, TEMP, PRES, DEWP, CO
        Missing columns (PM1.0, gas, MQ) are synthesised from the real data.
        """
        df = pd.read_csv(csv_path)
        df = self._adapt_beijing(df)
        df = self._clean(df)
        df = self._label(df)
        df = self._engineer_features(df)
        return self._split_episodes(df)

    def load_all(self, data_dir: str) -> list:
        """
        Load all CSV files in data_dir.
        Auto-detects format (hardware vs Beijing) by column names.
        """
        all_episodes = []
        data_path = Path(data_dir)

        for csv_file in data_path.glob('**/*.csv'):
            print(f"[Loader] Loading {csv_file.name} ...")
            try:
                raw = pd.read_csv(csv_file, nrows=2)
                if 'station' in raw.columns or 'DEWP' in raw.columns:
                    episodes = self.load_beijing(str(csv_file))
                elif 'timestamp' in raw.columns:
                    episodes = self.load_hardware(str(csv_file))
                else:
                    print(f"  Skipped (unknown format)")
                    continue
                all_episodes.extend(episodes)
                print(f"  → {len(episodes)} episodes")
            except Exception as e:
                print(f"  ERROR: {e}")

        print(f"[Loader] Total episodes: {len(all_episodes)}")
        return all_episodes

    # -----------------------------------------------------------------------
    # Beijing adapter
    # -----------------------------------------------------------------------

    def _adapt_beijing(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Map Beijing PRSA columns → Ember CSV format.
        Synthesises missing sensors (MQ, gas resistance) from available data.
        """
        out = pd.DataFrame()

        # Timestamp
        out['timestamp'] = pd.to_datetime({
            'year':   df['year'],
            'month':  df['month'],
            'day':    df['day'],
            'hour':   df['hour'],
        }, errors='coerce')

        # PM — direct columns
        out['PM2.5'] = pd.to_numeric(df['PM2.5'], errors='coerce')
        out['PM10']  = pd.to_numeric(df['PM10'],  errors='coerce')

        # PM1.0 — not in dataset, estimate as ~65% of PM2.5 (urban ratio)
        out['PM1.0'] = out['PM2.5'] * 0.65

        # ENS160 unavailable
        out['TVOC'] = 0
        out['eCO2'] = 0

        # Weather
        out['temperature'] = pd.to_numeric(df['TEMP'], errors='coerce')
        out['pressure']    = pd.to_numeric(df['PRES'], errors='coerce')

        # Humidity from dew point (Magnus approximation)
        T  = out['temperature']
        Td = pd.to_numeric(df['DEWP'], errors='coerce')
        out['humidity'] = 100.0 * np.exp(17.625 * Td / (243.04 + Td)) / \
                                  np.exp(17.625 * T  / (243.04 + T))
        out['humidity'] = out['humidity'].clip(0, 100)

        # Gas resistance — inversely correlated with PM2.5
        # High PM2.5 (> 150) → ~100K–300K Ohms; clean → 10M–20M Ohms
        pm25_norm   = (out['PM2.5'].clip(0, 300) / 300.0)
        out['gas']  = 15_000_000 * (1 - pm25_norm) + 100_000 * pm25_norm

        # MQ sensor voltage — synthesised from CO if available, else from PM2.5
        if 'CO' in df.columns:
            co = pd.to_numeric(df['CO'], errors='coerce').clip(0, 25)
            out['MQ_analog'] = ((co / 25.0) * 0.87 + 0.03).clip(0, 1)
        else:
            # Fallback: derive from PM2.5
            out['MQ_analog'] = (pm25_norm * 0.87 + 0.03).clip(0, 1)

        out['MQ_digital'] = (out['MQ_analog'] < (0.5 / 3.3)).astype(int)

        return out.dropna(subset=['PM2.5', 'PM10', 'temperature'])

    # -----------------------------------------------------------------------
    # Common preprocessing
    # -----------------------------------------------------------------------

    def _clean(self, df: pd.DataFrame) -> pd.DataFrame:
        """Drop rows with NaN in critical columns and reset index."""
        critical = ['PM2.5', 'PM10', 'MQ_analog']
        df = df.dropna(subset=critical).reset_index(drop=True)
        # Fill remaining NaN with 0 (matches hardware behaviour for missing ENS160)
        df = df.fillna(0)
        return df

    def _label(self, df: pd.DataFrame) -> pd.DataFrame:
        """Compute aqi_score and is_dangerous columns from raw sensor values."""
        mq_voltage    = df['MQ_analog'] * 3.3
        tvoc          = df['TVOC']  if 'TVOC'  in df.columns else 0
        eco2          = df['eCO2']  if 'eCO2'  in df.columns else 0
        df['aqi_score'] = [
            compute_composite_aqi(r['PM2.5'], r['PM10'], mq_v,
                                  r.get('TVOC', 0), r.get('eCO2', 0))
            for (_, r), mq_v in zip(df.iterrows(), mq_voltage)
        ]
        df['is_dangerous'] = df['aqi_score'].apply(is_dangerous).astype(int)
        return df

    def _engineer_features(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Add derived features suggested in SYSTEM_DOCUMENTATION.md Section 7.5.
        These expand the base 12 columns into the full 16-feature obs vector.
        """
        # Rate of change for primary PM2.5 sensor
        df['delta_pm25']   = df['PM2.5'].diff().fillna(0)
        df['delta_mq']     = df['MQ_analog'].diff().fillna(0)

        # 5-sample moving average to smooth noise
        df['pm25_avg5']    = df['PM2.5'].rolling(5, min_periods=1).mean()

        # BME680 gas resistance on log scale (lower log = worse air)
        df['log_gas']      = np.log10(df['gas'].clip(lower=10_000))

        # MQ temperature compensation (reduces drift)
        if 'temperature' in df.columns:
            df['mq_compensated'] = df['MQ_analog'] * 3.3 / \
                                   (1.0 + 0.02 * (df['temperature'] - 25.0)).clip(lower=0.1)
        else:
            df['mq_compensated'] = df['MQ_analog'] * 3.3

        # PM ratio — high ratio = fine particles (smoke)
        df['pm_ratio'] = df['PM2.5'] / df['PM10'].clip(lower=1)

        # Sensor agreement: how many sensors show elevated readings
        df['sensor_agreement'] = (
            (df['PM2.5'] > 35).astype(int) +
            (df['MQ_analog'] * 3.3 > 0.5).astype(int) +
            (df['log_gas'] < 6.0).astype(int)   # 6.0 = log10(1M Ohms)
        )

        # Alarm state (initialise to 0; env will maintain this dynamically)
        if 'alarm_active' not in df.columns:
            df['alarm_active'] = 0

        return df

    # -----------------------------------------------------------------------
    # Normalisation (raw → [0, 1])
    # -----------------------------------------------------------------------

    def normalize_obs(self, row: pd.Series) -> np.ndarray:
        """
        Convert a single DataFrame row into a normalised 16-float observation
        vector matching SYSTEM_DOCUMENTATION.md Section 7.1.
        """
        obs = np.zeros(16, dtype=np.float32)

        obs[0]  = float(row.get('PM1.0', 0))  / NORM['PM1.0'][1]
        obs[1]  = float(row.get('PM2.5', 0))  / NORM['PM2.5'][1]
        obs[2]  = float(row.get('PM10',  0))  / NORM['PM10'][1]
        obs[3]  = float(row.get('TVOC',  0))  / NORM['TVOC'][1]

        eco2    = max(float(row.get('eCO2', 0)) - NORM['eCO2_min'], 0.0)
        obs[4]  = eco2 / NORM['eCO2_range']

        obs[5]  = (float(row.get('temperature', 25)) - NORM['temperature'][0]) / 165.0
        obs[6]  = float(row.get('humidity',    50))  / NORM['humidity'][1]
        obs[7]  = (float(row.get('pressure', 1000)) - NORM['pressure'][0]) / NORM['pressure'][1]

        gas_raw = max(float(row.get('gas', 1_000_000)), 10_000)
        obs[8]  = np.log10(gas_raw) / NORM['gas_log_max']

        obs[9]  = (float(row.get('MQ_analog', 0)) * 3.3) / NORM['MQ_voltage'][1]
        obs[10] = float(row.get('MQ_digital', 1))

        # Feature flags — fixed for synthetic / derived from real data
        obs[11] = 1.0   # pms_valid
        obs[12] = 0.0   # ens160_available (ENS160 is disconnected)
        obs[13] = 1.0   # bme680_available

        obs[14] = float(row.get('aqi_score', 0))    / NORM['aqi'][1]
        obs[15] = float(row.get('alarm_active', 0))

        return np.clip(obs, 0.0, 1.0)

    # -----------------------------------------------------------------------
    # Episode splitter
    # -----------------------------------------------------------------------

    def _split_episodes(self, df: pd.DataFrame) -> list:
        """
        Split a DataFrame into overlapping fixed-length episodes.
        Each episode is a list of normalised obs vectors + danger labels.
        """
        episodes = []
        n = len(df)
        for start in range(0, n - self.episode_length + 1, self.stride):
            chunk = df.iloc[start: start + self.episode_length].reset_index(drop=True)
            obs_list = [self.normalize_obs(row) for _, row in chunk.iterrows()]
            label_list = chunk['is_dangerous'].tolist() if 'is_dangerous' in chunk else [0] * len(chunk)
            episodes.append({
                'obs':    obs_list,       # list of np.array (16,)
                'labels': label_list,     # list of int (0 or 1)
                'length': len(obs_list),
            })
        return episodes


# ---------------------------------------------------------------------------
# Quick test
# ---------------------------------------------------------------------------

if __name__ == '__main__':
    import sys
    loader = DataLoader(episode_length=60, stride=30)

    # Try to load synthetic data if it exists
    syn_path = os.path.join(os.path.dirname(__file__), '..', 'data', 'synthetic',
                            'synthetic_training_data.csv')
    if os.path.exists(syn_path):
        episodes = loader.load_synthetic(syn_path)
        print(f"Loaded {len(episodes)} episodes from synthetic data")
        print(f"First episode obs shape: {np.array(episodes[0]['obs']).shape}")
        print(f"First episode danger fraction: {sum(episodes[0]['labels'])/len(episodes[0]['labels']):.2f}")
    else:
        print("No synthetic data found. Run data_generator.py first.")
